### ISSUE TITLE
Custom Vuex Profile for Each Type of Stock Trader

### ISSUE THREAD

**Issue by wesdevpro** [ntohq/analyst#2]
# Feature
Allows a user to configure their experience as a trader. This feature will allow analysts to retrieve appropriate data from the API and the AI models. With this feature, personalized data can be utilized toward the trader's needs.

# Research:
[Day Trader Goals](https://www.investopedia.com/articles/trading/05/011705.asp)
       [Position Trader](https://www.investopedia.com/terms/p/positiontrader.asp)
[Long Term Trade Goals](https://www.investopedia.com/articles/fundamental-analysis/09/long-term-stock-pick.asp)
[Swing Trader Goals](https://www.investopedia.com/terms/s/swingtrading.asp)

# Tasks
1. Understand
    - [ ] Understand the methods each trader uses to reach their goals
    - [ ] Categorize each trader
    - [ ] Determine a ML model that would help each trader
2. Collect (Analyst API)
    - [ ] Determine the data for each model
    - [ ] Collect the Data
    - [ ] Push into Analyst API
3. Code
    - [ ]  Create ML model(s)
        - [ ] Train the Model
        - [ ] Test the Model with a https request
    - [ ]  Create analyst API endpoint
        - [ ] Create an AI function and Library
        - [ ] Test endpoint
    - [ ] Add Feature to analyst (web-app)
        - [ ] Create UI interface
            - [ ]  Configuration Input
            - [ ] Main page data input 
        - [ ] Create Vuex Logic
    - [ ] Test Intigration between web-app and the API
    - [ ] Test for Vulnerabilities
4. - [ ] Publish
